language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"
install:
  - pip install cython
  - pip install tqdm
  - pip install pupy
  - pip install pipenv
  - pipenv install -d --system
#  - pip install .
